listen: :443

tls:
  cert: /etc/ssl/certs/ssl-cert-snakeoil.pem
  key: /etc/ssl/private/ssl-cert-snakeoil.key

auth:
  type: password
  password: mystrongpassword123

masquerade:
  type: proxy
  proxy:
    url: https://www.cloudflare.com
    rewriteHost: true
